# Generated by Django 3.1 on 2020-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('cookie', models.TextField(null=True)),
                ('fa2', models.CharField(max_length=255)),
                ('number_of_friend', models.IntegerField(default=0)),
            ],
        ),
    ]
