# Generated by Django 3.1 on 2020-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
